[package]
name = "shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghostdb = {path = "../ghostdb"}
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
nanoid = "0.4.0"